remove u-boot extension to avoid error in linux-raspberrypi:do_bundle_initramfs recipe as it search for a specific pattern.
INITRAMFS_FSTYPES cannot be used to define the extension as it is used inside the recipe

ERROR: linux-raspberrypi-[...] do_bundle_initramfs: Could not find any [...]/core-image-readonly-rootfs-overlay-initramfs-raspberrypi3-64.cpio{.gz|.lz4|.lzo|.lzma|.xz|.zst)
for bundling; INITRAMFS_IMAGE_NAME might be wrong